/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    venues: Venue;
    beers: Beer;
    'tap-lists': TapList;
    events: Event;
    menus: Menu;
    'function-packages': FunctionPackage;
    pages: Page;
    posts: Post;
    merch: Merch;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    venues: VenuesSelect<false> | VenuesSelect<true>;
    beers: BeersSelect<false> | BeersSelect<true>;
    'tap-lists': TapListsSelect<false> | TapListsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'function-packages': FunctionPackagesSelect<false> | FunctionPackagesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    merch: MerchSelect<false> | MerchSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Address, hours and booking details. These drive the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  name: string;
  /**
   * Used in buttons, e.g. "Book West Perth".
   */
  shortName: string;
  /**
   * Used in the page URL. Change with care once live.
   */
  slug: string;
  address: {
    street: string;
    suburb: string;
    state?: string | null;
    postcode: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * e.g. "Directly opposite City West Station".
   */
  transportNote?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Shown above the hours, e.g. "Spring/Summer". The venues run seasonal hours, so say which season these are.
   */
  hoursLabel?: string | null;
  /**
   * One line about public holiday trading.
   */
  publicHolidayNote?: string | null;
  /**
   * One row per day. Leave open/close blank and tick Closed if you are shut that day.
   */
  openingHours?:
    | {
        day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        opens?: string | null;
        closes?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Public holidays and one-offs. These override the weekly hours for that date.
   */
  hoursOverrides?:
    | {
        date: string;
        label?: string | null;
        opens?: string | null;
        closes?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  amenities?:
    | (
        | 'Beer garden'
        | 'Kids zone'
        | 'Arcade games'
        | 'Dog friendly'
        | 'Ocean views'
        | 'Live music'
        | 'Wheelchair accessible'
        | 'Parking'
        | 'Function spaces'
        | 'Fresh seafood'
        | 'Family friendly'
        | 'Sports screens'
        | 'Outdoor seating'
      )[]
    | null;
  capacity?: number | null;
  tapCount?: number | null;
  /**
   * Answered on the venue page and marked up for Google.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * nowbookit booking URL. Opened in a modal on the site.
   */
  bookingUrl?: string | null;
  /**
   * me&u venue slug, used to sync menus and the tap list.
   */
  meanduSlug?: string | null;
  /**
   * Public me&u food menu URL.
   */
  menuUrl?: string | null;
  /**
   * Leave blank to fall back to the title and intro above.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for someone who cannot see it. Required — the old site had images with no description at all.
   */
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    can?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The full range. Everything here is searchable and gets its own page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beers".
 */
export interface Beer {
  id: number;
  name: string;
  /**
   * Used in the page URL. Change with care once live.
   */
  slug: string;
  style: string;
  /**
   * % by volume
   */
  abv: number;
  ibu?: number | null;
  category: 'core' | 'seasonal' | 'limited' | 'collab';
  /**
   * One or two lines. Shown on the beer card.
   */
  description?: string | null;
  tastingNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  canArtwork?: (number | null) | Media;
  /**
   * Product photography. The can shot above is used for cards and listings.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Declared on the product. Shown prominently on the beer page.
   */
  allergens?: ('Lactose' | 'Gluten' | 'Wheat' | 'Nuts' | 'Soy')[] | null;
  /**
   * Cube price in AUD, if sold online.
   */
  price?: number | null;
  packSize?: string | null;
  shopUrl?: string | null;
  /**
   * Which venues normally stock it. The live tap list is separate.
   */
  availableAt?: (number | Venue)[] | null;
  /**
   * Who grew and malted it. Shown on the beer page.
   */
  ingredients?:
    | {
        producer: string;
        contribution?: string | null;
        id?: string | null;
      }[]
    | null;
  untappdUrl?: string | null;
  /**
   * Leave blank to fall back to the title and intro above.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One per venue. Drag to reorder taps; tick "keg blown" when one runs out.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tap-lists".
 */
export interface TapList {
  id: number;
  title?: string | null;
  venue: number | Venue;
  taps?:
    | {
        tapNumber: number;
        /**
         * Leave blank for a guest tap.
         */
        beer?: (number | null) | Beer;
        kegBlown?: boolean | null;
        /**
         * Name, for a tap with no Beer record.
         */
        guestName?: string | null;
        guestStyle?: string | null;
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Set automatically when synced from me&u.
   */
  source?: ('manual' | 'meandu') | null;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything on at either venue. Give it real dates and it will retire itself.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Used in the page URL. Change with care once live.
   */
  slug: string;
  startsAt: string;
  endsAt?: string | null;
  /**
   * A weekly event is written once, not once per venue.
   */
  recurrence?: ('once' | 'weekly' | 'fortnightly' | 'monthly') | null;
  repeatsUntil?: string | null;
  venues: (number | Venue)[];
  category?: ('Quiz' | 'Live music' | 'Food special' | 'Beer release' | 'Sport' | 'Competition' | 'Other') | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isFree?: boolean | null;
  price?: string | null;
  bookingUrl?: string | null;
  /**
   * Leave blank to fall back to the title and intro above.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Synced from me&u. Edit menus in me&u, not here — this is a mirror.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  name: string;
  venue: number | Venue;
  meanduId?: string | null;
  syncedAt?: string | null;
  sections?:
    | {
        name?: string | null;
        items?:
          | {
              name?: string | null;
              price?: string | null;
              dietary?: string | null;
              description?: string | null;
              image?: (number | null) | Media;
              imageCredit?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private hire spaces and packages. Replaces the PDF-only page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "function-packages".
 */
export interface FunctionPackage {
  id: number;
  name: string;
  /**
   * Used in the page URL. Change with care once live.
   */
  slug: string;
  venue: number | Venue;
  capacity?: number | null;
  seating?: ('standing' | 'seated' | 'mixed') | null;
  priceGuide?: string | null;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional PDF, as a supplement rather than the only source.
   */
  brochure?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Build a page from blocks. Add, reorder and remove them freely.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Used in the page URL. Change with care once live.
   */
  slug: string;
  layout: (
    | {
        eyebrow?: string | null;
        heading: string;
        lede?: string | null;
        image?: (number | null) | Media;
        actions?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        heading?: string | null;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading?: string | null;
        venues: (number | Venue)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'venueCards';
      }
    | {
        heading?: string | null;
        filterBy?: ('all' | 'core' | 'seasonal' | 'limited') | null;
        limit?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'beerGrid';
      }
    | {
        heading?: string | null;
        /**
         * Leave blank for both venues.
         */
        venue?: (number | null) | Venue;
        limit?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'eventList';
      }
    | {
        heading?: string | null;
        venue: number | Venue;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tapList';
      }
    | {
        heading?: string | null;
        questions?:
          | {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        heading?: string | null;
        entries?:
          | {
              year: string;
              /**
               * Who gave it
               */
              body: string;
              /**
               * What it was for
               */
              detail?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'awards';
      }
    | {
        heading?: string | null;
        images: (number | Media)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        quote: string;
        attribution?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
  )[];
  /**
   * Leave blank to fall back to the title and intro above.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Used in the page URL. Change with care once live.
   */
  slug: string;
  publishedAt?: string | null;
  heroImage?: (number | null) | Media;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave blank to fall back to the title and intro above.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merch".
 */
export interface Merch {
  id: number;
  title: string;
  /**
   * Used in the page URL. Change with care once live.
   */
  slug: string;
  /**
   * In dollars. The site adds the currency, so enter 40 rather than A$40.00.
   */
  price?: number | null;
  /**
   * Hides the buy link and marks the item, rather than removing it.
   */
  soldOut?: boolean | null;
  /**
   * Where "Buy" goes. Empty means in-venue only.
   */
  shopUrl?: string | null;
  description?: string | null;
  /**
   * First image is the one shown in the shop grid. The rest appear on the item.
   */
  images?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Staff can change tap lists and events. Venue managers can also edit pages, beers and venues. Admins can do everything.
   */
  roles: ('admin' | 'venueManager' | 'staff')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'beers';
        value: number | Beer;
      } | null)
    | ({
        relationTo: 'tap-lists';
        value: number | TapList;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'function-packages';
        value: number | FunctionPackage;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'merch';
        value: number | Merch;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  address?:
    | T
    | {
        street?: T;
        suburb?: T;
        state?: T;
        postcode?: T;
        latitude?: T;
        longitude?: T;
      };
  transportNote?: T;
  phone?: T;
  email?: T;
  hoursLabel?: T;
  publicHolidayNote?: T;
  openingHours?:
    | T
    | {
        day?: T;
        opens?: T;
        closes?: T;
        closed?: T;
        id?: T;
      };
  hoursOverrides?:
    | T
    | {
        date?: T;
        label?: T;
        opens?: T;
        closes?: T;
        closed?: T;
        id?: T;
      };
  heroImage?: T;
  gallery?: T;
  intro?: T;
  amenities?: T;
  capacity?: T;
  tapCount?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  bookingUrl?: T;
  meanduSlug?: T;
  menuUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beers_select".
 */
export interface BeersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  style?: T;
  abv?: T;
  ibu?: T;
  category?: T;
  description?: T;
  tastingNotes?: T;
  canArtwork?: T;
  gallery?: T;
  allergens?: T;
  price?: T;
  packSize?: T;
  shopUrl?: T;
  availableAt?: T;
  ingredients?:
    | T
    | {
        producer?: T;
        contribution?: T;
        id?: T;
      };
  untappdUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tap-lists_select".
 */
export interface TapListsSelect<T extends boolean = true> {
  title?: T;
  venue?: T;
  taps?:
    | T
    | {
        tapNumber?: T;
        beer?: T;
        kegBlown?: T;
        guestName?: T;
        guestStyle?: T;
        price?: T;
        id?: T;
      };
  source?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startsAt?: T;
  endsAt?: T;
  recurrence?: T;
  repeatsUntil?: T;
  venues?: T;
  category?: T;
  heroImage?: T;
  body?: T;
  isFree?: T;
  price?: T;
  bookingUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  venue?: T;
  meanduId?: T;
  syncedAt?: T;
  sections?:
    | T
    | {
        name?: T;
        items?:
          | T
          | {
              name?: T;
              price?: T;
              dietary?: T;
              description?: T;
              image?: T;
              imageCredit?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "function-packages_select".
 */
export interface FunctionPackagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  venue?: T;
  capacity?: T;
  seating?: T;
  priceGuide?: T;
  image?: T;
  description?: T;
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  brochure?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lede?: T;
              image?: T;
              actions?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        venueCards?:
          | T
          | {
              heading?: T;
              venues?: T;
              id?: T;
              blockName?: T;
            };
        beerGrid?:
          | T
          | {
              heading?: T;
              filterBy?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        eventList?:
          | T
          | {
              heading?: T;
              venue?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        tapList?:
          | T
          | {
              heading?: T;
              venue?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              questions?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        awards?:
          | T
          | {
              heading?: T;
              entries?:
                | T
                | {
                    year?: T;
                    body?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  heroImage?: T;
  excerpt?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merch_select".
 */
export interface MerchSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  price?: T;
  soldOut?: T;
  shopUrl?: T;
  description?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        can?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  announcement?: string | null;
  announcementUrl?: string | null;
  /**
   * It disappears on its own after this date.
   */
  announcementUntil?: string | null;
  mainNav?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  bookingLabel?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  untappd?: string | null;
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  defaultImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  announcement?: T;
  announcementUrl?: T;
  announcementUntil?: T;
  mainNav?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  bookingLabel?: T;
  instagram?: T;
  facebook?: T;
  untappd?: T;
  defaultTitle?: T;
  defaultDescription?: T;
  defaultImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}