apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phatbrew
resources:
  - namespace.yaml
  - postgres.yaml
  - minio.yaml
  - mailpit.yaml
  - cms.yaml
  - web.yaml
  - migrate-job.yaml
  - seed-job.yaml
  - jobs.yaml
  - ingress.yaml
